---
# tasks file for install_gitlabrunner


  - name: Install Gitlab-runner repository
    yum_repository:
      name: gitlab-runner
      description: Install gitlab-runner
      baseurl: "{{ runner_url }}"
      gpgkey: "{{ runner_gpgkey }}"
      gpgcheck: yes
      sslcacert: /etc/pki/tls/certs/ca-bundle.crt
      sslverify: yes

  - name: Install gitlab-runner
    yum:
      name: "{{ runner_rpms }}"
      state: installed
