---
# tasks file for install_gitlabrunner


  - name: Install Gitlab-runner repository
    yum_repository:
      name: gitlab-runner
      description: Install gitlab-runner
      baseurl: https://packages.gitlab.com/runner/gitlab-runner/fedora/28/$basearch
      gpgkey: https://packages.gitlab.com/runner/gitlab-runner/gpgkey
      gpgcheck: yes
      sslcacert: /etc/pki/tls/certs/ca-bundle.crt
      sslverify: yes

  - name: Install gitlab-runner
    dnf:
      name: gitlab-runner
      state: installed

